name: CI

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      path:
        description: '下载'
        required: true
        default: 'you-got'
        
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10.14' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
    - run:  |
        pip install you-get
        mkdir tmp
        cd tmp
        you-get https://2475154810.tapecontent.net/radosgw/AXzQbboQ7phGW0/kWcC8ai-BaUQL1LqxLAircWVYuyENFc70o6K6P_Sfc0m-L-8oddFjtRPaNSfNjBbCTdepXC5d1vd5apRtBl73bSEpB_bIQYgHbamFh8mJqmubz53dnGwl3XbkB_oU7gXDl8ycYOyaaJ6zK7y282IA9oNdB_gkaonygv_Owz_txAyrVrtP_DNh62itHEN_H8oiKsHqOR2QHktiXAXlJXRB-C-7xbtosX6dLU-YjpcFlNXXzoTogoYvpEqrPoH3ZA945QHPgeql-_hIVuYRffsCaVe32gTZ7QkYJFsSw/H4610-ki240706-1080p.mp4
        cd ..
        ls -al ./tmp
        ls -al
        mv ./tmp/* ./tmp/1.mp4
        ls -al ./tmp
        
        

    - name: Upload release asset
      run: |
         pwd
         ls -al $GITHUB_WORKSPACE
        
    - uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.PTAKEN }}
          file: ./tmp/1.mp4
    
 
